import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 16 

[window]
opacity = 0.95
# blur = true
decorations = "Buttonless"
padding = { x = 0, y = 2 }

[keyboard]
# bindings = [ ]

[cursor]
style = { shape = "Beam"}
vi_mode_style = "Block"
