import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGS Nerd Font", style = "Regular" }
size = 16 

[window]
# opacity = 0.95
# blur = true
decorations = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true

[keyboard]
# use ctrl + number for selecting window
# https://github.com/alacritty/alacritty/issues/5680
bindings= [
  {key="Key0", mods= "Control", chars= "\u001b[48;5u" },
  {key="Key1", mods= "Control", chars= "\u001b[49;5u" },
  {key="Key2", mods= "Control", chars= "\u001b[50;5u" },
  {key="Key3", mods= "Control", chars= "\u001b[51;5u" },
  {key="Key4", mods= "Control", chars= "\u001b[52;5u" },
  {key="Key5", mods= "Control", chars= "\u001b[53;5u" },
  {key="Key6", mods= "Control", chars= "\u001b[54;5u" },
  {key="Key7", mods= "Control", chars= "\u001b[55;5u" },
  {key="Key8", mods= "Control", chars= "\u001b[56;5u" },
  {key="Key9", mods= "Control", chars= "\u001b[57;5u" }
]

[cursor]
style = { shape = "Underline"}
# vi_mode_style = "Block"
